language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kunyen811/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true kunyen811/docker-react npm run test -- --coverage
